version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
    restart: always
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    ports:
      - "8093:8093"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
    restart: always
    networks:
      - gitlab

networks:
  gitlab: {}

volumes:
  gitlab-data:
  gitlab-config:
  gitlab-runner-config:
